version: '3.5'
services:
  
  #Runby server setup:
  ruby:
    build:
      context: .
      dockerfile: Dockerfile
    
    #running sequence:
    depends_on:
      - database
      - redis
    ports:
      - "9000:4567"
    environment:
      DB: postgresql://postgres:password@database:5432
      CACHE: redis://:password@redis:6379

  #database setup:
  database:
    image: postgres:9.6.5
    environment:
      POSTGRES_PASSWORD: password
  
  #redis server setup:
  redis:
    image: redis
    command: redis-server --requirepass password
    environment:
      REDIS_PASSWORD: password
